### ISSUE TITLE
× Encountered error while trying to install package. ╰─> dpviewer

### ISSUE THREAD

**Issue by darldsla** [princeton-vl/DPVO_Docker#6]
```
Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/DPVO/DPViewer/setup.py", line 123, in <module>
          setup(
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 664, in run
          self.run_command('build')
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/DPVO/DPViewer/setup.py", line 116, in build_extension
          subprocess.check_call(
        File "/root/miniconda3/envs/dpvo/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--verbose', '-j']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dpviewer

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
(dpvo) root@System-Product-Name:/DPVO#
```

even using docker still facing the similar problem as in https://github.com/princeton-vl/DPVO issue

**Comment by jiaqingxie** [comment]
Hi. Are you trying to build with 11.8.1? Or something like <cuda_version>.1 ? I think there's a thread https://github.com/princeton-vl/DPVO_Docker/issues/2#issuecomment-1316192370 here that suggests to use 11.8.0 instead.

My platform:
1. Ubuntu **20.04**
2. CUDA Version: **12.0** (actual Version 11.6 by checking nvcc -V)
3. Installing with **11.8.0**

There exists some problem if you use the following settings, 
1. Ubuntu 22.04
2. CUDA Version: 12.0 (actual Version 11.8 by checking nvcc -V)
3. Installing with 11.8.1
So you could change to the above settings to avoid this issue. Hope this could help you.

**Comment by Launch-on-Titania** [comment]
> ```
> Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/DPVO/DPViewer/setup.py", line 123, in <module>
>           setup(
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
>           return distutils.core.setup(**attrs)
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
>           return run_commands(dist)
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
>           dist.run_commands()
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
>           self.run_command(cmd)
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
>           super().run_command(command)
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
>           cmd_obj.run()
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
>           return orig.install.run(self)
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 664, in run
>           self.run_command('build')
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
>           self.distribution.run_command(command)
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
>           super().run_command(command)
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
>           cmd_obj.run()
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
>           self.run_command(cmd_name)
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
>           self.distribution.run_command(command)
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
>           super().run_command(command)
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
>           cmd_obj.run()
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
>           _build_ext.run(self)
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
>           self.build_extensions()
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
>           self._build_extensions_serial()
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
>           self.build_extension(ext)
>         File "/DPVO/DPViewer/setup.py", line 116, in build_extension
>           subprocess.check_call(
>         File "/root/miniconda3/envs/dpvo/lib/python3.10/subprocess.py", line 369, in check_call
>           raise CalledProcessError(retcode, cmd)
>       subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--verbose', '-j']' returned non-zero exit status 2.
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: legacy-install-failure
> 
> × Encountered error while trying to install package.
> ╰─> dpviewer
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for output from the failure.
> (dpvo) root@System-Product-Name:/DPVO#
> ```
> 
> even using docker still facing the similar problem as in https://github.com/princeton-vl/DPVO issue

yeah I face the same issue. Have you solved this

**Comment by spagnoloG** [comment]
yes, you should install a more recent version of cmake. The problem is that the default Cmake in ubuntu image does not support the latest CUDA_VERSION compilation flags.

Do this to fix:
```bash
sudo apt purge -y cmake
wget https://github.com/Kitware/CMake/releases/download/v3.27.0/cmake-3.27.0-linux-x86_64.sh
chmod +x cmake-3.27.0-linux-x86_64.sh
./cmake-3.27.0-linux-x86_64.sh --skip-license --prefix=/usr/local
export PATH=/usr/local/bin:$PATH
pip install ./DPViewer
```

**Comment by deepConnectionism** [comment]
> yes, you should install a more recent version of cmake. The problem is that the default Cmake in ubuntu image does not support the latest CUDA_VERSION compilation flags.
> 
> Do this to fix:
> 
> ```shell
> sudo apt purge -y cmake
> wget https://github.com/Kitware/CMake/releases/download/v3.27.0/cmake-3.27.0-linux-x86_64.sh
> chmod +x cmake-3.27.0-linux-x86_64.sh
> ./cmake-3.27.0-linux-x86_64.sh --skip-license --prefix=/usr/local
> export PATH=/usr/local/bin:$PATH
> pip install ./DPViewer
> ```

Practice has shown that this is true, I encountered this mistake:

      CMake Error at /DPVO/DPViewer/build/temp.linux-x86_64-cpython-310/CMakeFiles/CMakeTmp/CMakeLists.txt:15 (add_executable):
        CUDA_STANDARD is set to invalid value '17'

      CMake Error at /usr/share/cmake-3.16/Modules/FindCUDA/select_compute_arch.cmake:114 (try_run):
        Failed to generate test project build system.
      Call Stack (most recent call first):
        CMakeLists.txt:15 (CUDA_DETECT_INSTALLED_GPUS)

My Solution:
```bash
wget https://cmake.org/files/v3.27/cmake-3.27.0-linux-x86_64.sh
chmod +x cmake-3.27.0-linux-x86_64.sh
sh ./cmake-3.27.0-linux-x86_64.sh --skip-licence --prefix=/usr/local --exclude-subdir
echo 'export PATH=/usr/local/bin:$PATH' >> ~/.bashrc
source ~/.bashrc
cmake --version
```
